import Foundation

/// First-launch rules transcribed from the user's `Cotabby-Extended-Context.md`. They are ordinary
/// editable rules after installation: the defaults are written only when no correction database
/// exists, so deleting or changing one is respected on every later launch.
nonisolated enum PersonalCorrectionDefaults {
    static let rules: [PersonalCorrectionRule] = mappings.map { trigger, replacement in
        PersonalCorrectionRule(
            trigger: trigger,
            replacement: replacement,
            caseMode: .exact,
            action: .automatic,
            source: .bundledStarter
        )
    }

    private static let mappings: [(String, String)] = [
        ("ot", "to"),
        ("im", "I'm"),
        ("cottaby", "Cotabby"),
        ("nad", "and"),
        ("adn", "and"),
        ("hte", "the"),
        ("teh", "the"),
        ("thier", "their"),
        ("speeling", "spelling"),
        ("spellling", "spelling"),
        ("implenmentation", "implementation"),
        ("implemenation", "implementation"),
        ("featue", "feature"),
        ("featuere", "feature"),
        ("everyhting", "everything"),
        ("thourouhgly", "thoroughly"),
        ("thoroughy", "thoroughly"),
        ("distrbuted", "distributed"),
        ("distrubuted", "distributed"),
        ("ocne", "once"),
        ("muhc", "much"),
        ("hwo", "how"),
        ("wrok", "work"),
        ("wroks", "works"),
        ("becuase", "because"),
        ("becasue", "because"),
        ("recieve", "receive"),
        ("seperate", "separate"),
        ("definately", "definitely"),
        ("neccessary", "necessary"),
        ("occurence", "occurrence"),
        ("langauge", "language"),
        ("grammer", "grammar"),
        ("prediciton", "prediction"),
        ("predicitve", "predictive"),
        ("correciton", "correction"),
        ("aplication", "application"),
        ("applicaiton", "application"),
        ("accesibility", "accessibility"),
        ("infernece", "inference"),
        ("optmize", "optimize"),
        ("optmization", "optimization"),
        ("quantizaton", "quantization"),
        ("cahce", "cache"),
        ("keystorke", "keystroke"),
        ("conext", "context"),
        ("mdoel", "model"),
        ("modle", "model"),
        ("repositroy", "repository"),
        ("wiht", "with"),
        ("woudl", "would"),
        ("shoudl", "should"),
        ("coudl", "could"),
        ("taht", "that"),
        ("tihs", "this"),
        ("jsut", "just"),
        ("knwo", "know"),
        ("waht", "what"),
        ("whcih", "which"),
        ("ahve", "have"),
        ("hvae", "have"),
        ("form", "from"),
        ("dont", "don't"),
        ("doesnt", "doesn't"),
        ("didnt", "didn't"),
        ("cant", "can't"),
        ("wont", "won't"),
        ("ive", "I've"),
        ("ill", "I'll"),
        ("id", "I'd"),
        ("u", "you"),
        ("fiel", "file"),
        ("get chat", "this chat"),
        ("thx", "thanks.")
    ]
}
